name: Reverter commits errados

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  revert:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Reverter commits errados
        run: |
          git revert --no-edit 7be8b0d
          git revert --no-edit 05b02b0
          git revert --no-edit 114975b

      - name: Enviar correção
        run: git push
